# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andreabortolossi/Desktop/CODICI/TUTORIAL_CODE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andreabortolossi/Desktop/CODICI/TUTORIAL_CODE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andreabortolossi/Desktop/CODICI/TUTORIAL_CODE/CMakeFiles /Users/andreabortolossi/Desktop/CODICI/TUTORIAL_CODE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andreabortolossi/Desktop/CODICI/TUTORIAL_CODE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Geometry

# Build rule for target.
Geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Geometry
.PHONY : Geometry

# fast build rule for target.
Geometry/fast:
	$(MAKE) -f Geometry/CMakeFiles/Geometry.dir/build.make Geometry/CMakeFiles/Geometry.dir/build
.PHONY : Geometry/fast

#=============================================================================
# Target rules for targets named Quadrature

# Build rule for target.
Quadrature: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Quadrature
.PHONY : Quadrature

# fast build rule for target.
Quadrature/fast:
	$(MAKE) -f Quadrature/CMakeFiles/Quadrature.dir/build.make Quadrature/CMakeFiles/Quadrature.dir/build
.PHONY : Quadrature/fast

#=============================================================================
# Target rules for targets named QuadratureRules

# Build rule for target.
QuadratureRules: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QuadratureRules
.PHONY : QuadratureRules

# fast build rule for target.
QuadratureRules/fast:
	$(MAKE) -f QuadratureRules/CMakeFiles/QuadratureRules.dir/build.make QuadratureRules/CMakeFiles/QuadratureRules.dir/build
.PHONY : QuadratureRules/fast

#=============================================================================
# Target rules for targets named MyQuadRules

# Build rule for target.
MyQuadRules: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyQuadRules
.PHONY : MyQuadRules

# fast build rule for target.
MyQuadRules/fast:
	$(MAKE) -f FactoryQuad/CMakeFiles/MyQuadRules.dir/build.make FactoryQuad/CMakeFiles/MyQuadRules.dir/build
.PHONY : MyQuadRules/fast

#=============================================================================
# Target rules for targets named TestQuad

# Build rule for target.
TestQuad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestQuad
.PHONY : TestQuad

# fast build rule for target.
TestQuad/fast:
	$(MAKE) -f TestQuad/CMakeFiles/TestQuad.dir/build.make TestQuad/CMakeFiles/TestQuad.dir/build
.PHONY : TestQuad/fast

#=============================================================================
# Target rules for targets named TestQuad1D

# Build rule for target.
TestQuad1D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestQuad1D
.PHONY : TestQuad1D

# fast build rule for target.
TestQuad1D/fast:
	$(MAKE) -f TestQuad1D/CMakeFiles/TestQuad1D.dir/build.make TestQuad1D/CMakeFiles/TestQuad1D.dir/build
.PHONY : TestQuad1D/fast

#=============================================================================
# Target rules for targets named TestGeometry

# Build rule for target.
TestGeometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestGeometry
.PHONY : TestGeometry

# fast build rule for target.
TestGeometry/fast:
	$(MAKE) -f TestGeometry/CMakeFiles/TestGeometry.dir/build.make TestGeometry/CMakeFiles/TestGeometry.dir/build
.PHONY : TestGeometry/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Geometry"
	@echo "... Quadrature"
	@echo "... QuadratureRules"
	@echo "... MyQuadRules"
	@echo "... TestQuad"
	@echo "... TestQuad1D"
	@echo "... TestGeometry"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

